In [1]:
#Code with the the topic : Cross validation

#Descripcion:

#Este modelo tiene como proposito predecir las probabilidades de que una persona tenga Diabetes o NO 
#basado en los datos CSV y se estara aplicando la estructura de prueba de cross validation 
#(fit/cross_val_score)

#Tecnologias usadas:

#Visual Studio Code
#Python
#Sklearn
#Pandas
#Jupyter notebook

#Como usar el codigo ?

#Este modelo es una prueba de codigo que se basa en estructurar y experimentar con el tema : Cross 
#validation

#Resultados: 

#Apesar de ya tener un dataset anterior el codigo nos ayuda a distinguir en que momento usar el fit 
#y cross_val_score

#Porque se usa este tema?

#para evitar que el modelo memorice los datos y verificar si predice bien

In [2]:
#Importamos las librerias que estaremos usando 

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
#Dejamos que pandas lea el archivo csv y lo convierta

datos = pd.read_csv("DiabetesSioNo.csv")

In [3]:
#Observamos los datos en tabla

datos.head()

   Edad   IMC  Glucosa  Presion  Insulina  Actividad_Fisica  Diabetes
0    25  22.5       90       70        80                 5         0
1    34  28.1      140       85       130                 1         1
2    45  31.2      160       90       150                 0         1
3    29  24.3      100       75        85                 4         0
4    52  33.5      180       95       170                 0         1

In [4]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Edad              15 non-null     int64
 1   IMC               15 non-null     float64
 2   Glucosa           15 non-null     int64
 3   Presion           15 non-null     int64
 4   Insulina          15 non-null     int64
 5   Actividad_Fisica  15 non-null     int64
 6   Diabetes          15 non-null     int64
dtypes: float64(1), int64(6)
memory usage: 972.0 bytes

In [5]:
datos.describe()

,Edad,IMC,Glucosa,Presion,Insulina,Actividad_Fisica,Diabetes
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,39.266667,28.366667,134.666667,83.933333,125.133333,2.066667,0.533333
std,11.310341,4.161330,35.074750,9.974730,38.843765,1.944467,0.516398
min,23.000000,21.700000,85.000000,68.000000,70.000000,0.000000,0.000000
25%,30.000000,25.150000,105.000000,76.500000,90.000000,0.500000,0.000000
50%,39.000000,28.900000,135.000000,85.000000,120.000000,2.000000,1.000000
75%,46.500000,30.800000,157.500000,91.000000,155.000000,3.500000,1.000000
max,60.000000,35.000000,200.000000,100.000000,190.000000,6.000000,1.000000

In [6]:
#Es recomendable usar columns para no confundirse escribiendo mal el nombre de las variables

datos.columns

Index(['Edad', 'IMC', 'Glucosa', 'Presion', 'Insulina', 'Actividad_Fisica',
       'Diabetes'],
      dtype='object')

In [7]:
#Definimos X y Y colocandoles las variables 

x = datos[["Edad","IMC","Glucosa","Presion","Insulina","Actividad_Fisica"]]
y = datos["Diabetes"]

In [8]:
#como los tenemos ya definidos en este caso primero usaremos la estructura de fit :
#FIT :
#Entrena y prueba una sola vez
#Tiene mas riesgo de overfitting 
#Entrena con los datos que tiene 
#Es mas rapido 
#No recomendable usar con pocos datos

#1 separamos el modelo con train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [9]:
#2 Creamos el modelo y lo entrenamos
modelo = LogisticRegression(max_iter=1000)
modelo.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [10]:
#3 Lo evaluamos 
pre = modelo.predict(x_test)

In [11]:
accuracy = accuracy_score(y_test,pre)
print(accuracy)

0.6666666666666666

In [12]:
#El accuracy indica el porcentaje de predicciones correctas del modelo.
#Por ejemplo, 0.66 significa que el modelo acierta aproximadamente el 66% de las veces.

In [13]:
datos.head()

   Edad   IMC  Glucosa  Presion  Insulina  Actividad_Fisica  Diabetes
0    25  22.5       90       70        80                 5         0
1    34  28.1      140       85       130                 1         1
2    45  31.2      160       90       150                 0         1
3    29  24.3      100       75        85                 4         0
4    52  33.5      180       95       170                 0         1

In [14]:
#Hacemos una prediccion de prueba

nueva_prediccion = [[28,23.2,70,90,2,0]]
prediccion= modelo.predict(nueva_prediccion)

if prediccion[0] == 1:
    print("Tienes Diabetes")
else:
    print("No tienes Diabetes")

No tienes Diabetes

c:\Users\Selene\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [15]:
#Ahora usaremos Cross_val_score

cross = cross_val_score(modelo,x,y, cv=5)
print(cross)

[1. 1. 1. 1. 1.]

In [16]:
#El modelo se entrena 5 veces usando diferentes divisiones de los datos.
#Cada valor representa el accuracy obtenido en cada fold.
#Podemos calcular el promedio para obtener el rendimiento general.

In [17]:
#Verificamos el rednimiento del modelo:

modelo.score(x,y)

0.9333333333333333