#Code with thw topic : Sensitivity and Specifity

#Descripcion:
#This model proposes to classify whether a customer will pay for a subscription or not based on logistic regression and uses Sensitivity and Specificity.

#Technologies used:

#pandas
#Jupyter notebook
#Sklearn
#Python
#Visual Code Studio

#Method used:

#Logistic Regression

#How to use the code 

#This model aims to explain the uses of sensitivity and specificity.

In [1]:
#We import the libraries

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,recall_score

In [2]:
#We process the CSV file so that the model can read it.
datos = pd.read_csv("Suscripcion.csv")

In [3]:
#We see the data in a table.
datos.head()

   ClienteID  Edad  Plan  UsoMensualHoras  SoporteLlamadas  Chrun
0          1    25     1               10                1      0
1          2    40     3               30                0      0
2          3    32     1                5                2      1
3          4    28     2               15                0      0
4          5    50     3               40                3      0

In [4]:
datos.describe()

,ClienteID,Edad,Plan,UsoMensualHoras,SoporteLlamadas,Chrun
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,5.50000,33.400000,1.900000,16.700000,1.400000,0.300000
std,3.02765,9.070097,0.875595,12.009718,1.349897,0.483046
min,1.00000,22.000000,1.000000,2.000000,0.000000,0.000000
25%,3.25000,27.250000,1.000000,8.500000,0.250000,0.000000
50%,5.50000,31.000000,2.000000,13.500000,1.000000,0.000000
75%,7.75000,38.750000,2.750000,23.750000,2.000000,0.750000
max,10.00000,50.000000,3.000000,40.000000,4.000000,1.000000

In [5]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ClienteID        10 non-null     int64
 1   Edad             10 non-null     int64
 2   Plan             10 non-null     int64
 3   UsoMensualHoras  10 non-null     int64
 4   SoporteLlamadas  10 non-null     int64
 5   Chrun            10 non-null     int64
dtypes: int64(6)
memory usage: 612.0 bytes

In [6]:
#We use columns to avoid confusion with variables
datos.columns

Index(['ClienteID', 'Edad', 'Plan', 'UsoMensualHoras', 'SoporteLlamadas',
       'Chrun'],
      dtype='object')

In [7]:
#We define X and Y to separate the variables
X = datos[["Edad","Plan","UsoMensualHoras","SoporteLlamadas"]]
Y = datos["Chrun"]

In [17]:
# convert categories
X = pd.get_dummies(X, drop_first=True)
print(X)

   Edad  Plan  UsoMensualHoras  SoporteLlamadas
0    25     1               10                1
1    40     3               30                0
2    32     1                5                2
3    28     2               15                0
4    50     3               40                3
5    22     1                2                4
6    35     2               20                1
7    45     3               25                0
8    30     1                8                2
9    27     2               12                1

In [9]:
#We separate training and testing
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [10]:
#We created the model and trained it
modelo = LogisticRegression()
modelo.fit(x_train,y_train)

LogisticRegression()

In [11]:
pre = modelo.predict(x_test)

In [12]:
#We used recall to see how many true positives the model found.
sensitivity = recall_score(y_test,pre)
print(sensitivity)

1.0

In [13]:
#We use the confusion matrix to observe performance
cm = confusion_matrix(y_test,pre)

In [14]:
TN,FP,FN,TP = cm.ravel()

In [15]:

Specificity = TN/(TN+FP)
print("Specificity: ",Specificity)

Specificity:  1.0

In [16]:
print("Confusion matrix",cm)

Confusion matrix [[1 0]
 [0 1]]